// Datos de siembra del catálogo configurable — Fase 11 del roadmap (ver
// auditoría "Manual Ruta de Emprendimiento FUMC", §07/§08, C1-C5).
//
// Todo el catálogo que exige el Manual (agosto 2026, MEUNE-FUMC) se siembra
// de una sola vez: 3 fases, las 5 etapas actuales sin modificar, y los 30
// instrumentos de las secciones 6 y 7. Nada de esto se "construye cuando se
// necesite" — el Administrador solo activa o desactiva lo que ya existe
// desde /configuracion.
//
// Los campos de cada instrumento están tomados literalmente de las tablas
// de diligenciamiento del Manual cuando el documento las especifica (los 13
// de Fase 1 y 5 de los 17 de Fase 2 tienen tabla propia). Los 12 restantes
// de Fase 2 solo tienen nombre y propósito en el Manual (son plantillas de
// documento, no formularios de campos) — se les dio un esquema mínimo
// razonable, editable después desde /configuracion sin tocar código.

import type { CampoInstrumentoDef } from "../src/lib/catalogo/tipos";

export interface FaseSeed {
  clave: string;
  nombre: string;
  descripcion: string;
  orden: number;
}

export interface EtapaSeed {
  clave: string;
  nombre: string;
  color: string;
  orden: number;
}

export interface InstrumentoSeed {
  clave: string;
  nombre: string;
  proposito: string;
  origenManual: string;
  faseClave: "pre_incubacion" | "incubacion";
  momento: string;
  responsableDiligencia: string;
  responsableRevisa: string;
  orden: number;
  campos: CampoInstrumentoDef[];
}

export const FASES_SEED: FaseSeed[] = [
  {
    clave: "pre_incubacion",
    nombre: "Pre-incubación",
    descripcion:
      "Sensibilización, ideación y validación temprana del problema. Filtrar ideas, validar el problema y formar al emprendedor en fundamentos.",
    orden: 1,
  },
  {
    clave: "incubacion",
    nombre: "Incubación",
    descripcion:
      "Estructuración, validación del modelo de negocio y preparación para escalamiento inicial.",
    orden: 2,
  },
  {
    clave: "egreso",
    nombre: "Egreso / Post-incubación",
    descripcion: "Cierre de la ruta y seguimiento opcional a la sostenibilidad del emprendimiento.",
    orden: 3,
  },
];

// Las 5 etapas actuales, sin modificar — misma `clave` que ya vive como
// string en Emprendedor.etapa. Se dejan sin `faseId` por defecto: la
// relación entre etapa y fase es una decisión del Administrador, no una
// regla fija del sistema (ver auditoría §07).
export const ETAPAS_SEED: EtapaSeed[] = [
  { clave: "Descubrir", nombre: "Descubrir", color: "var(--etapa-descubrir)", orden: 1 },
  { clave: "Incubar", nombre: "Incubar", color: "var(--etapa-incubar)", orden: 2 },
  { clave: "Formar", nombre: "Formar", color: "var(--etapa-formar)", orden: 3 },
  { clave: "Fomentar", nombre: "Fomentar", color: "var(--etapa-fomentar)", orden: 4 },
  { clave: "Financiar", nombre: "Financiar", color: "var(--etapa-financiar)", orden: 5 },
];

const SI_NO = ["Sí", "No"];

export const INSTRUMENTOS_SEED: InstrumentoSeed[] = [
  // ------------------------------------------------------------------
  // Fase 1 — Pre-incubación (Manual §6, 13 instrumentos con tabla propia)
  // ------------------------------------------------------------------
  {
    clave: "ficha_inscripcion",
    nombre: "Ficha de inscripción / postulación",
    proposito: "Registrar datos del emprendedor o equipo y su motivación para ingresar a la ruta.",
    origenManual: "6.1",
    faseClave: "pre_incubacion",
    momento: "Ingreso a la ruta",
    responsableDiligencia: "Emprendedor",
    responsableRevisa: "Asesor",
    orden: 1,
    campos: [
      { clave: "nombreProvisional", etiqueta: "Nombre provisional del emprendimiento", tipo: "texto", requerido: true },
      { clave: "fechaPostulacion", etiqueta: "Fecha de postulación", tipo: "fecha", requerido: true },
      { clave: "canalPostulacion", etiqueta: "Canal de postulación", tipo: "seleccion", requerido: true, opciones: ["Formulario web", "Feria", "Referido", "Otro"] },
      { clave: "integrantesEquipo", etiqueta: "Integrantes del equipo (nombre, documento, programa, semestre, correo, teléfono — uno por línea)", tipo: "textarea", requerido: true },
      { clave: "comoSeEntero", etiqueta: "¿Cómo se enteró de la Ruta de Emprendimiento?", tipo: "texto" },
      { clave: "motivacion", etiqueta: "Motivación para postularse", tipo: "textarea", requerido: true },
      { clave: "expectativas", etiqueta: "Expectativas frente al acompañamiento", tipo: "textarea" },
      { clave: "disponibilidadHoras", etiqueta: "Disponibilidad de tiempo semanal (horas)", tipo: "numero" },
      { clave: "firmaPostulante", etiqueta: "Firma del postulante", tipo: "texto", requerido: true },
    ],
  },
  {
    clave: "ficha_caracterizacion",
    nombre: "Ficha de caracterización del emprendimiento",
    proposito: "Clasificar el sector, la etapa y el tipo de innovación (base tecnológica, social, tradicional).",
    origenManual: "6.2",
    faseClave: "pre_incubacion",
    momento: "Ingreso a la ruta",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 2,
    campos: [
      { clave: "nombreEmprendimiento", etiqueta: "Nombre del emprendimiento", tipo: "texto", requerido: true },
      { clave: "nombresEmprendedores", etiqueta: "Nombre(s) del emprendedor(es)", tipo: "textarea", requerido: true },
      { clave: "programaFacultad", etiqueta: "Programa académico / Facultad", tipo: "texto" },
      { clave: "sede", etiqueta: "Sede", tipo: "seleccion", requerido: true, opciones: ["Medellín", "Neiva", "Popayán"] },
      { clave: "fechaIngreso", etiqueta: "Fecha de ingreso a la ruta", tipo: "fecha", requerido: true },
      { clave: "sectorEconomico", etiqueta: "Sector económico", tipo: "texto", requerido: true },
      { clave: "tipoInnovacion", etiqueta: "Tipo de innovación", tipo: "seleccion", requerido: true, opciones: ["Base tecnológica", "Social", "Tradicional"] },
      { clave: "madurez", etiqueta: "Etapa actual del emprendimiento", tipo: "seleccion", requerido: true, opciones: ["Idea", "Prototipo", "Operando"] },
      { clave: "descripcionIdea", etiqueta: "Breve descripción de la idea de negocio", tipo: "textarea", requerido: true },
      { clave: "problema", etiqueta: "Problema que busca resolver", tipo: "textarea", requerido: true },
      { clave: "asesorAsignado", etiqueta: "Asesor(a) asignado(a)", tipo: "texto" },
    ],
  },
  {
    clave: "rubrica_seleccion_ideas",
    nombre: "Rúbrica de evaluación y selección de ideas",
    proposito: "Filtrar ideas con criterios objetivos: innovación, viabilidad, equipo emprendedor.",
    origenManual: "6.3",
    faseClave: "pre_incubacion",
    momento: "Selección",
    responsableDiligencia: "Asesor / comité evaluador",
    responsableRevisa: "Coordinador",
    orden: 3,
    campos: [
      { clave: "puntajeInnovacion", etiqueta: "Innovación (1-5)", tipo: "numero", requerido: true },
      { clave: "puntajeViabilidadTecnica", etiqueta: "Viabilidad técnica (1-5)", tipo: "numero", requerido: true },
      { clave: "puntajeViabilidadComercial", etiqueta: "Viabilidad comercial (1-5)", tipo: "numero", requerido: true },
      { clave: "puntajeEquipo", etiqueta: "Equipo emprendedor (1-5)", tipo: "numero", requerido: true },
      { clave: "puntajeImpacto", etiqueta: "Impacto social, ambiental o económico (1-5)", tipo: "numero", requerido: true },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
      { clave: "decision", etiqueta: "Decisión", tipo: "seleccion", requerido: true, opciones: ["Admite a pre-incubación", "Admite con ajustes", "No admite"] },
      { clave: "evaluadores", etiqueta: "Evaluador(es)", tipo: "texto", requerido: true },
    ],
  },
  {
    clave: "mapa_empatia",
    nombre: "Mapa de empatía",
    proposito: "Comprender a profundidad al usuario o cliente objetivo.",
    origenManual: "6.4",
    faseClave: "pre_incubacion",
    momento: "Ideación",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 4,
    campos: [
      { clave: "pienseYSiente", etiqueta: "¿Qué piensa y siente?", tipo: "textarea" },
      { clave: "queVe", etiqueta: "¿Qué ve?", tipo: "textarea" },
      { clave: "queEscucha", etiqueta: "¿Qué escucha?", tipo: "textarea" },
      { clave: "diceYHace", etiqueta: "¿Qué dice y hace?", tipo: "textarea" },
      { clave: "esfuerzosFrustraciones", etiqueta: "Esfuerzos / frustraciones", tipo: "textarea" },
      { clave: "resultadosBeneficios", etiqueta: "Resultados / beneficios que busca", tipo: "textarea" },
    ],
  },
  {
    clave: "customer_discovery",
    nombre: "Formato de Customer Discovery (entrevista de problema)",
    proposito: "Validar que el problema identificado es real y relevante para el segmento.",
    origenManual: "6.5",
    faseClave: "pre_incubacion",
    momento: "Validación temprana",
    responsableDiligencia: "Emprendedor",
    responsableRevisa: "Asesor",
    orden: 5,
    campos: [
      { clave: "personaEntrevistada", etiqueta: "Persona entrevistada (rol / segmento)", tipo: "texto", requerido: true },
      { clave: "fechaEntrevista", etiqueta: "Fecha de la entrevista", tipo: "fecha", requerido: true },
      { clave: "problemaExplorado", etiqueta: "Problema explorado", tipo: "textarea", requerido: true },
      { clave: "reconoceProblema", etiqueta: "¿Reconoce el problema como algo relevante?", tipo: "seleccion", opciones: SI_NO },
      { clave: "evidenciaReconocimiento", etiqueta: "Evidencia", tipo: "textarea" },
      { clave: "frecuenciaIntensidad", etiqueta: "Frecuencia / intensidad con la que vive el problema", tipo: "textarea" },
      { clave: "solucionesActuales", etiqueta: "Soluciones actuales que usa para resolverlo", tipo: "textarea" },
      { clave: "disposicionPagar", etiqueta: "Disposición a pagar por una solución", tipo: "seleccion", opciones: SI_NO },
      { clave: "cuantoPagaria", etiqueta: "¿Cuánto?", tipo: "texto" },
      { clave: "insightsClave", etiqueta: "Insights clave de la entrevista", tipo: "textarea" },
      { clave: "conclusionValidacion", etiqueta: "Conclusión: ¿se valida el problema?", tipo: "seleccion", opciones: ["Se valida", "No se valida"] },
    ],
  },
  {
    clave: "bmc_inicial",
    nombre: "Business Model Canvas (versión inicial)",
    proposito: "Construir una visión general del modelo de negocio en formación.",
    origenManual: "6.6",
    faseClave: "pre_incubacion",
    momento: "Ideación — se itera en incubación en cada gate",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 6,
    campos: [
      { clave: "sociosClave", etiqueta: "Socios clave", tipo: "textarea" },
      { clave: "actividadesClave", etiqueta: "Actividades clave", tipo: "textarea" },
      { clave: "recursosClave", etiqueta: "Recursos clave", tipo: "textarea" },
      { clave: "propuestaValor", etiqueta: "Propuesta de valor", tipo: "textarea", requerido: true },
      { clave: "relacionClientes", etiqueta: "Relación con clientes", tipo: "textarea" },
      { clave: "canales", etiqueta: "Canales", tipo: "textarea" },
      { clave: "segmentosClientes", etiqueta: "Segmentos de clientes", tipo: "textarea", requerido: true },
      { clave: "estructuraCostos", etiqueta: "Estructura de costos", tipo: "textarea" },
      { clave: "fuentesIngresos", etiqueta: "Fuentes de ingresos", tipo: "textarea" },
    ],
  },
  {
    clave: "vpc",
    nombre: "Value Proposition Canvas",
    proposito: "Ajustar la propuesta de valor a los dolores y alegrías del cliente.",
    origenManual: "6.7",
    faseClave: "pre_incubacion",
    momento: "Ideación",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 7,
    campos: [
      { clave: "alegriasCliente", etiqueta: "Alegrías (ganancias esperadas)", tipo: "textarea" },
      { clave: "frustracionesCliente", etiqueta: "Frustraciones (dolores)", tipo: "textarea" },
      { clave: "trabajosCliente", etiqueta: "Trabajos del cliente (qué intenta lograr)", tipo: "textarea" },
      { clave: "creadoresAlegrias", etiqueta: "Creadores de alegrías", tipo: "textarea" },
      { clave: "aliviadoresFrustraciones", etiqueta: "Aliviadores de frustraciones", tipo: "textarea" },
      { clave: "productosServicios", etiqueta: "Productos y servicios", tipo: "textarea" },
    ],
  },
  {
    clave: "matriz_dofa",
    nombre: "Matriz DOFA",
    proposito: "Diagnosticar fortalezas, oportunidades, debilidades y amenazas iniciales.",
    origenManual: "6.8",
    faseClave: "pre_incubacion",
    momento: "Ideación",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 8,
    campos: [
      { clave: "debilidades", etiqueta: "Debilidades (interno)", tipo: "textarea" },
      { clave: "oportunidades", etiqueta: "Oportunidades (externo)", tipo: "textarea" },
      { clave: "fortalezas", etiqueta: "Fortalezas (interno)", tipo: "textarea" },
      { clave: "amenazas", etiqueta: "Amenazas (externo)", tipo: "textarea" },
    ],
  },
  {
    clave: "tablero_design_thinking",
    nombre: "Tablero Design Thinking",
    proposito: "Estructurar el proceso creativo de principio a fin.",
    origenManual: "6.9",
    faseClave: "pre_incubacion",
    momento: "Transversal a la fase",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 9,
    campos: [
      { clave: "empatizarActividades", etiqueta: "Empatizar — actividades realizadas", tipo: "textarea" },
      { clave: "empatizarHallazgos", etiqueta: "Empatizar — hallazgos / resultados", tipo: "textarea" },
      { clave: "empatizarFecha", etiqueta: "Empatizar — fecha", tipo: "fecha" },
      { clave: "definirActividades", etiqueta: "Definir — actividades realizadas", tipo: "textarea" },
      { clave: "definirHallazgos", etiqueta: "Definir — hallazgos / resultados", tipo: "textarea" },
      { clave: "definirFecha", etiqueta: "Definir — fecha", tipo: "fecha" },
      { clave: "idearActividades", etiqueta: "Idear — actividades realizadas", tipo: "textarea" },
      { clave: "idearHallazgos", etiqueta: "Idear — hallazgos / resultados", tipo: "textarea" },
      { clave: "idearFecha", etiqueta: "Idear — fecha", tipo: "fecha" },
      { clave: "prototiparActividades", etiqueta: "Prototipar — actividades realizadas", tipo: "textarea" },
      { clave: "prototiparHallazgos", etiqueta: "Prototipar — hallazgos / resultados", tipo: "textarea" },
      { clave: "prototiparFecha", etiqueta: "Prototipar — fecha", tipo: "fecha" },
      { clave: "testearActividades", etiqueta: "Testear — actividades realizadas", tipo: "textarea" },
      { clave: "testearHallazgos", etiqueta: "Testear — hallazgos / resultados", tipo: "textarea" },
      { clave: "testearFecha", etiqueta: "Testear — fecha", tipo: "fecha" },
    ],
  },
  {
    clave: "bitacora_mentoria",
    nombre: "Bitácora de mentoría / acompañamiento",
    proposito: "Registrar cada sesión de asesoría, compromisos y avances.",
    origenManual: "6.10",
    faseClave: "pre_incubacion",
    momento: "Cada sesión",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 10,
    campos: [
      { clave: "fechaSesion", etiqueta: "Fecha de la sesión", tipo: "fecha", requerido: true },
      { clave: "asesor", etiqueta: "Asesor(a)", tipo: "texto", requerido: true },
      { clave: "modalidad", etiqueta: "Modalidad", tipo: "seleccion", opciones: ["Presencial", "Virtual"] },
      { clave: "temasTratados", etiqueta: "Temas tratados", tipo: "textarea", requerido: true },
      { clave: "compromisosEmprendedor", etiqueta: "Compromisos del emprendedor", tipo: "textarea" },
      { clave: "compromisosAsesor", etiqueta: "Compromisos del asesor", tipo: "textarea" },
      { clave: "proximaSesion", etiqueta: "Próxima sesión (fecha)", tipo: "fecha" },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
    ],
  },
  {
    clave: "acta_compromiso",
    nombre: "Acta de compromiso / carta de aceptación a la ruta",
    proposito: "Formalizar reglas, tiempos y responsabilidades entre las partes.",
    origenManual: "6.11",
    faseClave: "pre_incubacion",
    momento: "Ingreso a la ruta",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 11,
    campos: [
      { clave: "integrantesEquipo", etiqueta: "Integrantes del equipo", tipo: "textarea", requerido: true },
      { clave: "fechaIngreso", etiqueta: "Fecha de ingreso", tipo: "fecha", requerido: true },
      { clave: "compromisosFUMC", etiqueta: "Compromisos de la Fundación Universitaria María Cano", tipo: "textarea", requerido: true },
      { clave: "compromisosEmprendedor", etiqueta: "Compromisos del emprendedor", tipo: "textarea", requerido: true },
      { clave: "duracionEstimada", etiqueta: "Duración estimada del acompañamiento en esta fase", tipo: "texto" },
      { clave: "causalesRetiro", etiqueta: "Causales de retiro de la ruta", tipo: "textarea" },
      { clave: "firmaEmprendedor", etiqueta: "Firma del emprendedor", tipo: "texto", requerido: true },
      { clave: "firmaAsesor", etiqueta: "Firma del asesor / coordinador de la ruta", tipo: "texto", requerido: true },
    ],
  },
  {
    clave: "consentimiento_datos",
    nombre: "Consentimiento informado y manejo de datos / PI",
    proposito: "Proteger la confidencialidad de la idea y los datos personales del equipo.",
    origenManual: "6.12",
    faseClave: "pre_incubacion",
    momento: "Ingreso a la ruta",
    responsableDiligencia: "Emprendedor",
    responsableRevisa: "Asesor",
    orden: 12,
    campos: [
      { clave: "autorizaTratamientoDatos", etiqueta: "Autorización de tratamiento de datos personales (Ley 1581 de 2012)", tipo: "booleano", requerido: true },
      { clave: "declaraTitularidadIdea", etiqueta: "Declaración de titularidad de la idea de negocio por parte del equipo", tipo: "booleano", requerido: true },
      { clave: "autorizaUsoEstadistico", etiqueta: "Autorización de uso de la información con fines de reporte institucional y estadístico, anonimizada", tipo: "booleano", requerido: true },
      { clave: "compromisoConfidencialidad", etiqueta: "Compromiso de confidencialidad por parte de la Fundación y sus asesores", tipo: "textarea" },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
      { clave: "firmaEmprendedor", etiqueta: "Firma del emprendedor", tipo: "texto", requerido: true },
      { clave: "firmaAsesor", etiqueta: "Firma del asesor / responsable institucional", tipo: "texto", requerido: true },
    ],
  },
  {
    clave: "transito_pre_incubacion_incubacion",
    nombre: "Formato de tránsito de fase (gate pre-incubación → incubación)",
    proposito: "Evaluar si el emprendimiento está listo para avanzar de fase.",
    origenManual: "6.13",
    faseClave: "pre_incubacion",
    momento: "Salida de la fase",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 13,
    campos: [
      { clave: "fechaEvaluacion", etiqueta: "Fecha de evaluación", tipo: "fecha", requerido: true },
      { clave: "problemaValidado", etiqueta: "Criterio 1: problema validado", tipo: "booleano", requerido: true },
      { clave: "evidenciaProblema", etiqueta: "Evidencia", tipo: "textarea" },
      { clave: "modeloConsistente", etiqueta: "Criterio 2: modelo de negocio consistente", tipo: "booleano", requerido: true },
      { clave: "evidenciaModelo", etiqueta: "Evidencia", tipo: "textarea" },
      { clave: "equipoComprometido", etiqueta: "Criterio 3: equipo comprometido y activo", tipo: "booleano", requerido: true },
      { clave: "evidenciaEquipo", etiqueta: "Evidencia", tipo: "textarea" },
      { clave: "decision", etiqueta: "Decisión", tipo: "seleccion", requerido: true, opciones: ["Avanza a incubación", "Se mantiene en pre-incubación", "Se retira"] },
      { clave: "firmaAsesor", etiqueta: "Asesor(a) que evalúa — firma", tipo: "texto", requerido: true },
    ],
  },

  // ------------------------------------------------------------------
  // Fase 2 — Incubación (Manual §7, 17 instrumentos de la tabla resumen;
  // 5 de ellos con tabla de diligenciamiento propia en el Manual)
  // ------------------------------------------------------------------
  {
    clave: "bmc_validado",
    nombre: "Business Model Canvas (versión validada e iterada)",
    proposito: "Consolidar el modelo de negocio con evidencia real de mercado.",
    origenManual: "7·1",
    faseClave: "incubacion",
    momento: "Inicio de incubación",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 14,
    campos: [
      { clave: "sociosClave", etiqueta: "Socios clave", tipo: "textarea" },
      { clave: "actividadesClave", etiqueta: "Actividades clave", tipo: "textarea" },
      { clave: "recursosClave", etiqueta: "Recursos clave", tipo: "textarea" },
      { clave: "propuestaValor", etiqueta: "Propuesta de valor", tipo: "textarea", requerido: true },
      { clave: "relacionClientes", etiqueta: "Relación con clientes", tipo: "textarea" },
      { clave: "canales", etiqueta: "Canales", tipo: "textarea" },
      { clave: "segmentosClientes", etiqueta: "Segmentos de clientes", tipo: "textarea", requerido: true },
      { clave: "estructuraCostos", etiqueta: "Estructura de costos", tipo: "textarea" },
      { clave: "fuentesIngresos", etiqueta: "Fuentes de ingresos", tipo: "textarea" },
      { clave: "evidenciaMercado", etiqueta: "Evidencia real de mercado que sustenta esta versión", tipo: "textarea", requerido: true },
    ],
  },
  {
    clave: "plan_negocio",
    nombre: "Plan de negocio estructurado",
    proposito: "Guía estructurada para transformar una idea en un proyecto comercial viable, minimizando riesgos y orientando la toma de decisiones.",
    origenManual: "7·2",
    faseClave: "incubacion",
    momento: "A lo largo de la fase",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 15,
    campos: [
      { clave: "resumenEjecutivo", etiqueta: "Resumen ejecutivo", tipo: "textarea", requerido: true },
      { clave: "archivoReferencia", etiqueta: "Documento adjunto (nombre de archivo)", tipo: "texto" },
      { clave: "fechaUltimaActualizacion", etiqueta: "Fecha de última actualización", tipo: "fecha" },
      { clave: "observaciones", etiqueta: "Observaciones del asesor", tipo: "textarea" },
    ],
  },
  {
    clave: "modelo_financiero",
    nombre: "Modelo financiero (P&G, flujo de caja, punto de equilibrio)",
    proposito: "Sustentar la viabilidad financiera del emprendimiento.",
    origenManual: "7·3",
    faseClave: "incubacion",
    momento: "Estructuración",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 16,
    campos: [
      { clave: "puntoEquilibrio", etiqueta: "Punto de equilibrio estimado", tipo: "texto" },
      { clave: "resumenFlujoCaja", etiqueta: "Resumen del flujo de caja proyectado", tipo: "textarea" },
      { clave: "archivoReferencia", etiqueta: "Modelo adjunto (nombre de archivo)", tipo: "texto" },
      { clave: "fechaUltimaActualizacion", etiqueta: "Fecha de última actualización", tipo: "fecha" },
      { clave: "observaciones", etiqueta: "Observaciones del asesor", tipo: "textarea" },
    ],
  },
  {
    clave: "validacion_mvp",
    nombre: "Formato de validación de MVP (experimentos Lean Startup)",
    proposito: "Documentar hipótesis, experimentos y aprendizajes obtenidos.",
    origenManual: "7·4",
    faseClave: "incubacion",
    momento: "Validación",
    responsableDiligencia: "Emprendedor",
    responsableRevisa: "Asesor",
    orden: 17,
    campos: [
      { clave: "hipotesis", etiqueta: "Hipótesis a validar", tipo: "textarea", requerido: true },
      { clave: "experimento", etiqueta: "Experimento diseñado (qué se va a hacer)", tipo: "textarea", requerido: true },
      { clave: "metricaExito", etiqueta: "Métrica de éxito (criterio cuantificable)", tipo: "texto", requerido: true },
      { clave: "fechaInicio", etiqueta: "Fecha de inicio del experimento", tipo: "fecha" },
      { clave: "fechaFin", etiqueta: "Fecha de fin del experimento", tipo: "fecha" },
      { clave: "resultadoObtenido", etiqueta: "Resultado obtenido", tipo: "textarea" },
      { clave: "seValida", etiqueta: "¿Se valida o se invalida la hipótesis?", tipo: "seleccion", opciones: ["Se valida", "Se invalida"] },
      { clave: "aprendizajeClave", etiqueta: "Aprendizaje clave", tipo: "textarea" },
      { clave: "proximoPaso", etiqueta: "Próximo paso", tipo: "seleccion", opciones: ["Pivotar", "Perseverar"] },
    ],
  },
  {
    clave: "estudio_mercado",
    nombre: "Estudio de mercado (tamaño, competencia, segmentación)",
    proposito: "Sustentar decisiones comerciales con datos de mercado.",
    origenManual: "7·5",
    faseClave: "incubacion",
    momento: "Estructuración",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 18,
    campos: [
      { clave: "tamanoMercado", etiqueta: "Tamaño de mercado estimado", tipo: "texto" },
      { clave: "competencia", etiqueta: "Competencia identificada", tipo: "textarea" },
      { clave: "segmentacion", etiqueta: "Segmentación de clientes", tipo: "textarea" },
      { clave: "archivoReferencia", etiqueta: "Estudio adjunto (nombre de archivo)", tipo: "texto" },
      { clave: "observaciones", etiqueta: "Observaciones del asesor", tipo: "textarea" },
    ],
  },
  {
    clave: "matriz_riesgos",
    nombre: "Matriz de riesgos",
    proposito: "Identificar y mitigar los riesgos críticos del negocio.",
    origenManual: "7·6",
    faseClave: "incubacion",
    momento: "Estructuración",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 19,
    campos: [
      { clave: "riesgoIdentificado", etiqueta: "Riesgo identificado", tipo: "textarea", requerido: true },
      { clave: "tipoRiesgo", etiqueta: "Tipo", tipo: "seleccion", opciones: ["Mercado", "Financiero", "Legal", "Técnico"] },
      { clave: "probabilidad", etiqueta: "Probabilidad", tipo: "seleccion", opciones: ["Alta", "Media", "Baja"] },
      { clave: "impacto", etiqueta: "Impacto", tipo: "seleccion", opciones: ["Alto", "Medio", "Bajo"] },
      { clave: "accionMitigacion", etiqueta: "Acción de mitigación", tipo: "textarea", requerido: true },
    ],
  },
  {
    clave: "roadmap_hitos",
    nombre: "Roadmap / plan de trabajo con hitos",
    proposito: "Establecer cronograma de metas técnicas y comerciales.",
    origenManual: "7·7",
    faseClave: "incubacion",
    momento: "Estructuración",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 20,
    campos: [
      { clave: "hito", etiqueta: "Hito", tipo: "texto", requerido: true },
      { clave: "fechaMeta", etiqueta: "Fecha meta", tipo: "fecha", requerido: true },
      { clave: "estado", etiqueta: "Estado", tipo: "seleccion", opciones: ["Pendiente", "En curso", "Cumplido", "Atrasado"] },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
    ],
  },
  {
    clave: "kpis_impacto",
    nombre: "Formato de seguimiento de KPIs / indicadores de impacto",
    proposito: "Medir tracción: ventas, usuarios, empleos generados.",
    origenManual: "7·8",
    faseClave: "incubacion",
    momento: "Seguimiento periódico",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 21,
    campos: [
      { clave: "ventasIngresos", etiqueta: "Ventas / ingresos — meta", tipo: "numero" },
      { clave: "ventasIngresosResultado", etiqueta: "Ventas / ingresos — resultado del periodo", tipo: "numero" },
      { clave: "usuariosActivos", etiqueta: "Usuarios o clientes activos — meta", tipo: "numero" },
      { clave: "usuariosActivosResultado", etiqueta: "Usuarios o clientes activos — resultado del periodo", tipo: "numero" },
      { clave: "empleosGenerados", etiqueta: "Empleos generados — meta", tipo: "numero" },
      { clave: "empleosGeneradosResultado", etiqueta: "Empleos generados — resultado del periodo", tipo: "numero" },
      { clave: "avanceMvpPct", etiqueta: "Avance del MVP (%)", tipo: "numero" },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
    ],
  },
  {
    clave: "bitacora_especializada",
    nombre: "Bitácora de mentoría especializada",
    proposito: "Registrar asesorías técnicas, financieras, legales y comerciales.",
    origenManual: "7·9",
    faseClave: "incubacion",
    momento: "Cada sesión",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 22,
    campos: [
      { clave: "fechaSesion", etiqueta: "Fecha de la sesión", tipo: "fecha", requerido: true },
      { clave: "tipoAsesoria", etiqueta: "Tipo de asesoría", tipo: "seleccion", opciones: ["Técnica", "Financiera", "Legal", "Comercial"] },
      { clave: "asesor", etiqueta: "Asesor(a)", tipo: "texto", requerido: true },
      { clave: "temasTratados", etiqueta: "Temas tratados", tipo: "textarea", requerido: true },
      { clave: "compromisos", etiqueta: "Compromisos derivados", tipo: "textarea" },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
    ],
  },
  {
    clave: "estructura_legal_tributaria",
    nombre: "Formato de estructura legal y tributaria",
    proposito: "Orientar la constitución formal de la empresa, si aplica.",
    origenManual: "7·10",
    faseClave: "incubacion",
    momento: "Estructuración",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 23,
    campos: [
      { clave: "tipoSociedad", etiqueta: "Tipo de figura societaria considerada", tipo: "texto" },
      { clave: "estadoConstitucion", etiqueta: "Estado de constitución", tipo: "seleccion", opciones: ["No iniciado", "En trámite", "Constituida"] },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
    ],
  },
  {
    clave: "propiedad_intelectual",
    nombre: "Formato de propiedad intelectual / registro de marca o patente",
    proposito: "Proteger los activos intangibles del emprendimiento.",
    origenManual: "7·11",
    faseClave: "incubacion",
    momento: "Cuando aplique",
    responsableDiligencia: "Emprendedor, con el asesor",
    responsableRevisa: "Asesor",
    orden: 24,
    campos: [
      { clave: "tipoProteccion", etiqueta: "Tipo de protección", tipo: "seleccion", opciones: ["Marca", "Patente", "Derecho de autor", "Ninguno"] },
      { clave: "estado", etiqueta: "Estado", tipo: "seleccion", opciones: ["No iniciado", "En trámite", "Registrado"] },
      { clave: "numeroRadicado", etiqueta: "Número de radicado", tipo: "texto" },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
    ],
  },
  {
    clave: "pitch_deck",
    nombre: "Plantilla de Pitch Deck",
    proposito: "Estandarizar la presentación ante inversionistas o jurados.",
    origenManual: "7·12",
    faseClave: "incubacion",
    momento: "Preparación de pitch",
    responsableDiligencia: "Emprendedor",
    responsableRevisa: "Asesor",
    orden: 25,
    campos: [
      { clave: "archivoReferencia", etiqueta: "Pitch deck adjunto (nombre de archivo)", tipo: "texto", requerido: true },
      { clave: "fechaVersion", etiqueta: "Fecha de esta versión", tipo: "fecha" },
      { clave: "observaciones", etiqueta: "Observaciones del asesor", tipo: "textarea" },
    ],
  },
  {
    clave: "rubrica_pitch",
    nombre: "Rúbrica de evaluación de pitch",
    proposito: "Dar retroalimentación estructurada tras cada presentación.",
    origenManual: "7·13",
    faseClave: "incubacion",
    momento: "Eventos de pitch (ej. Pitch MEUNE)",
    responsableDiligencia: "Jurado / asesor evaluador",
    responsableRevisa: "Coordinador",
    orden: 26,
    campos: [
      { clave: "claridadProblemaSolucion", etiqueta: "Claridad del problema y la solución (1-5)", tipo: "numero", requerido: true },
      { clave: "validacionEvidencia", etiqueta: "Validación / evidencia presentada (1-5)", tipo: "numero", requerido: true },
      { clave: "modeloViabilidad", etiqueta: "Modelo de negocio y viabilidad financiera (1-5)", tipo: "numero", requerido: true },
      { clave: "equipoEmprendedor", etiqueta: "Equipo emprendedor (1-5)", tipo: "numero", requerido: true },
      { clave: "calidadPresentacion", etiqueta: "Calidad de la presentación (pitch deck y oralidad) (1-5)", tipo: "numero", requerido: true },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
      { clave: "recomendacion", etiqueta: "Recomendación", tipo: "textarea" },
    ],
  },
  {
    clave: "postulacion_convocatorias",
    nombre: "Formato de postulación a convocatorias externas",
    proposito: "Enlazar al emprendimiento con financiamiento.",
    origenManual: "7·14",
    faseClave: "incubacion",
    momento: "Cuando aplique",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 27,
    campos: [
      { clave: "convocatoria", etiqueta: "Convocatoria (ej. Fondo Emprender, CONPES 4130)", tipo: "texto", requerido: true },
      { clave: "fechaPostulacion", etiqueta: "Fecha de postulación", tipo: "fecha" },
      { clave: "estado", etiqueta: "Estado", tipo: "seleccion", opciones: ["Postulado", "En evaluación", "Aprobado", "Rechazado"] },
      { clave: "resultado", etiqueta: "Resultado / observaciones", tipo: "textarea" },
    ],
  },
  {
    clave: "encuesta_satisfaccion",
    nombre: "Encuesta de satisfacción del emprendedor",
    proposito: "Evaluar la calidad del acompañamiento recibido.",
    origenManual: "7·15",
    faseClave: "incubacion",
    momento: "Cierre de fase",
    responsableDiligencia: "Emprendedor",
    responsableRevisa: "Coordinador",
    orden: 28,
    campos: [
      { clave: "faseCursada", etiqueta: "Fase cursada", tipo: "seleccion", opciones: ["Pre-incubación", "Incubación"] },
      { clave: "calificacionGeneral", etiqueta: "Calificación general del acompañamiento (1-5)", tipo: "numero", requerido: true },
      { clave: "metodologiaUtil", etiqueta: "¿La metodología usada le fue útil?", tipo: "seleccion", opciones: SI_NO },
      { clave: "porQueMetodologia", etiqueta: "¿Por qué?", tipo: "textarea" },
      { clave: "asesorCumplioTiempos", etiqueta: "¿El asesor cumplió los tiempos y compromisos?", tipo: "seleccion", opciones: SI_NO },
      { clave: "aspectosPorMejorar", etiqueta: "Aspectos por mejorar", tipo: "textarea" },
      { clave: "comentariosAdicionales", etiqueta: "Comentarios adicionales", tipo: "textarea" },
    ],
  },
  {
    clave: "certificado_graduacion",
    nombre: "Certificado de graduación / informe de cierre de ruta",
    proposito: "Dejar evidencia institucional del proceso completo.",
    origenManual: "7·16",
    faseClave: "incubacion",
    momento: "Cierre",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 29,
    campos: [
      { clave: "fechaCierre", etiqueta: "Fecha de cierre de la ruta", tipo: "fecha", requerido: true },
      { clave: "resumenRecorrido", etiqueta: "Resumen del recorrido longitudinal", tipo: "textarea", requerido: true },
      { clave: "decisionFinal", etiqueta: "Decisión final", tipo: "seleccion", opciones: ["Gradúa", "Continúa en incubación", "Se retira"] },
      { clave: "firmaCoordinador", etiqueta: "Firma del coordinador de la ruta", tipo: "texto" },
    ],
  },
  {
    clave: "seguimiento_post_incubacion",
    nombre: "Formato de seguimiento post-incubación",
    proposito: "Monitorear la sostenibilidad del emprendimiento tras salir de la ruta.",
    origenManual: "7·17",
    faseClave: "incubacion",
    momento: "Post-cierre (opcional)",
    responsableDiligencia: "Asesor",
    responsableRevisa: "Coordinador",
    orden: 30,
    campos: [
      { clave: "fechaSeguimiento", etiqueta: "Fecha de seguimiento", tipo: "fecha", requerido: true },
      { clave: "estadoNegocio", etiqueta: "Estado actual del negocio", tipo: "texto" },
      { clave: "ventasActuales", etiqueta: "Ventas actuales", tipo: "numero" },
      { clave: "empleosActuales", etiqueta: "Empleos actuales", tipo: "numero" },
      { clave: "observaciones", etiqueta: "Observaciones", tipo: "textarea" },
    ],
  },
];
